@if (isset($current_facility))
    <li @if ($current_route == 'facility')class="active"@endif><a href="{{ route('facility', ['id' => $current_facility->id]) }}"><i class="glyphicon glyphicon-home"></i> Tableau de bord</a></li>
    @if (in_array(1, $current_facility->tabs))<li @if ($current_tab == 1)class="active"@endif><a href="{{ route('facility_tab', ['id' => $current_facility->id, 'tab' => 1]) }}"><i class="glyphicon glyphicon-signal"></i> Débit</a></li>@endif
    @if (in_array(2, $current_facility->tabs))<li @if ($current_tab == 2)class="active"@endif><a href="{{ route('facility_tab', ['id' => $current_facility->id, 'tab' => 2]) }}"><i class="fa fa-tint"></i> Volume</a></li>@endif
    @if (in_array(3, $current_facility->tabs))<li @if ($current_tab == 3)class="active"@endif><a href="{{ route('facility_tab', ['id' => $current_facility->id, 'tab' => 3]) }}"><i class="glyphicon glyphicon-tasks"></i> Composition</a></li>@endif
    @if (in_array(4, $current_facility->tabs))<li @if ($current_tab == 4)class="active"@endif><a href="{{ route('facility_tab', ['id' => $current_facility->id, 'tab' => 4]) }}"><i class="glyphicon glyphicon-log-in"></i> Suivi prétraitement</a></li>@endif
    @if (in_array(5, $current_facility->tabs))<li @if ($current_tab == 5)class="active"@endif><a href="{{ route('facility_tab', ['id' => $current_facility->id, 'tab' => 5]) }}"><i class="fa fa-map-marker"></i> Indicateur IGP</a></li>@endif
    @if (in_array(6, $current_facility->tabs))<li @if ($current_tab == 6)class="active"@endif><a href="{{ route('facility_tab', ['id' => $current_facility->id, 'tab' => 6]) }}"><i class="glyphicon glyphicon-flash"></i> Consommation électrique</a></li>@endif
    @if (in_array(7, $current_facility->tabs))<li @if ($current_tab == 7)class="active"@endif><a href="{{ route('facility_tab', ['id' => $current_facility->id, 'tab' => 7]) }}"><i class="glyphicon glyphicon-scale"></i> Puissance digesteurs</a></li>@endif
    @if (in_array(8, $current_facility->tabs))<li @if ($current_tab == 8)class="active"@endif><a href="{{ route('facility_tab', ['id' => $current_facility->id, 'tab' => 8]) }}"><i class="glyphicon glyphicon-time"></i> Heures en fonctionnement</a></li>@endif
    @if (in_array(9, $current_facility->tabs))<li @if ($current_tab == 9)class="active"@endif><a href="{{ route('facility_tab', ['id' => $current_facility->id, 'tab' => 9]) }}"><i class="glyphicon glyphicon-exclamation-sign"></i> Historique des alarmes</a></li>@endif
    @if (in_array(10, $current_facility->tabs))<li @if ($current_tab == 10)class="active"@endif><a href="{{ route('facility_tab', ['id' => $current_facility->id, 'tab' => 10]) }}"><i class="glyphicon glyphicon-check"></i> Maintenance</a></li>@endif
    @if (in_array(11, $current_facility->tabs))<li @if ($current_tab == 11)class="active"@endif><a href="{{ route('facility_tab', ['id' => $current_facility->id, 'tab' => 11]) }}"><i class="glyphicon glyphicon-folder-open"></i> Fichiers de données</a></li>@endif
@endif